spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gz-cynosdbmysql-grp-84tdgg43.sql.tencentcdb.com:25120/db?serverTimezone=UTC
    username: root
    password: gdupt@3c807
  thymeleaf:
    cache: false        # 禁用缓存
    mode: LEGACYHTML5   # 非严格型检查 默认是html 严格检查
  application:
    name: pyScript
server:
  port: 9999
pyScript:
  python:
    script:
      path: src/main/resources/static/py/word.py
    path: C:\\Users\\I\\AppData\\Local\\Programs\\Python\\Python39
#mybatis-plus日志
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
