spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gz-cynosdbmysql-grp-84tdgg43.sql.tencentcdb.com:25120/db?serverTimezone=UTC
    username: root
    password: gdupt@3c807
  thymeleaf:
    cache: false        # 禁用缓存
    mode: LEGACYHTML5   # 非严格型检查 默认是html 严格检查
  application:
    name: pyScript
server:
  port: 8080
pyScript:
  python:
    script:
      path: E:\\code\\gitRepository\\problemSystem-K\\src\\main\\resources\\static\\py\\test.py
    path: C:\Users\l\AppData\Local\Programs\Python\Python39\\python.exe
#mybatis-plus日志
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
