spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db?serverTimezone=UTC
    username: root
    password: 1234
  thymeleaf:
    cache: false        # 禁用缓存
    mode: LEGACYHTML5   # 非严格型检查 默认是html 严格检查

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
